#!/usr/bin/env node
'use strict';
/**
 * One-off rebrand helper: Moderntech -> Zanatechnologies
 *
 * Run from the templates/ folder:
 *   node rebrand.js           dry run: lists every file and how many replacements it would make
 *   node rebrand.js --write   applies the replacements
 *
 * Only the exact, capitalised word "Moderntech" is replaced. Anything else that
 * looks like the old name (moderntech in a URL or email, "Modern Tech", MODERNTECH)
 * is listed under REVIEW so you can decide by hand. The out/ scratch folder,
 * node_modules and .git are skipped because out/ is regenerated by `publish`.
 */
const fs = require('fs');
const path = require('path');

const OLD = 'Moderntech';
const NEW = 'Zanatechnologies';
const WRITE = process.argv.includes('--write');
const ROOT = __dirname;
const SKIP_DIRS = new Set(['out', 'node_modules', '.git']);
const EXT = /\.(json|html|js|md)$/i;

const files = [];
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) { if (!SKIP_DIRS.has(e.name)) walk(full); }
    else if (EXT.test(e.name) && e.name !== 'rebrand.js') files.push(full);
  }
})(ROOT);

let total = 0, changedFiles = 0;
const review = [];

for (const file of files) {
  const before = fs.readFileSync(file, 'utf8');
  const count = before.split(OLD).length - 1;
  const after = before.split(OLD).join(NEW);

  after.split(/\r?\n/).forEach((line, i) => {
    if (/modern\s?tech/i.test(line)) {
      review.push(`${path.relative(ROOT, file)}:${i + 1}  ${line.trim().slice(0, 140)}`);
    }
  });

  if (count > 0) {
    total += count; changedFiles++;
    console.log(`${String(count).padStart(3)}  ${path.relative(ROOT, file)}`);
    if (WRITE) fs.writeFileSync(file, after, 'utf8');
  }
}

console.log(`\n${WRITE ? 'Replaced' : 'Would replace'} ${total} occurrence(s) in ${changedFiles} file(s).`);
if (review.length) {
  console.log('\nREVIEW (left unchanged, other spellings of the old name):');
  review.forEach(r => console.log('  ' + r));
}
if (!WRITE) console.log('\nDry run only. Run "node rebrand.js --write" to apply.');
